name: HELLO World Script
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest #sepcifying runner machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Hello World
        run: echo "Hello World"

      - name: Print my working Directory
        run: pwd

      - name: Create a textfile
        run: touch myfile.txt
      
      - name: Adding text inside the textfile
        run : echo "This is a file" > myfile.txt 
      
      - name: Pushing it it my repo 
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Added the file"
          git push origin HEAD:main
        env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
