name: HELLO World Script
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Hello World
        run: echo "Hello World"

      - name: Print my working Directory
        run: pwd

      - name: Create a textfile
        run: touch myfile.txt
