name: Hello World Script
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Hello World Script
        run: echo "Hello, World!"
        
      - name: Run a multi-line script
        run: |
          echo "This is a multi-line script."
          echo "It can run multiple commands."
          echo "Goodbye, World!"
      - name: Display current directory
        run: pwd
      - name: Create a Text File 
        run: touch example.txt 