name: Third yaml script

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      people-output: ${{ steps.set-matrix.outputs.people-output }}
    steps:
      - name: Setting up the matrix in build job
        id: set-matrix
        run: |
          PEOPLE='[
            { "name": "Tayyab", "age": 20, "gender": "Male" },
            { "name": "Armaghan", "age": 22, "gender": "Male" },
            { "name": "Ayesha", "age": 19, "gender": "Female" },
            { "name": "Umar", "age": 18, "gender": "Male" },
            { "name": "Ahmed", "age": 21, "gender": "Male" }
          ]'
          echo "people-matrix=$PEOPLE" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        person: ${{ fromJson(needs.build.outputs.people-matrix) }}
    steps:
      - name: Print person info
        run: |
          echo "Name: ${{ matrix.person.name }}"
          echo "Age: ${{ matrix.person.age }}"
          echo "Gender: ${{ matrix.person.gender }}"
