name: Third yaml script

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        People:
          - { name: "Tayyab", age: 20, gender: "Male" }
          - { name: "Armaghan", age: 22, gender: "Male" }
          - { name: "Ayesha", age: 19, gender: "Female" }
          - { name: "Umar", age: 18, gender: "Male" }
          - { name: "Ahmed", age: 21, gender: "Male" }

    steps:
      - name: Printing personal information
        run: |
          NAME="${{ matrix.People.name }}"
          AGE="${{ matrix.People.age }}"
          GENDER="${{ matrix.People.gender }}"

          echo "Name is: $NAME"
          echo "Age is: $AGE"
          echo "Gender is: $GENDER"
